### PR TITLE
Fix(Save Image)

### PR DESCRIPTION
**Pull request by polokoio456**

### CODE REVIEW

**Comment by polokoio456** [comment]
JPG File has no alpha value so I remove the options.

**Comment by Piasy** [comment]
Hi @polokoio456 , thanks for you PR, but I'm not sure if it's a good idea to change the image format from PNG to JPEG.

**Comment by polokoio456** [comment]
Because I set the ContentValue that JPG format, I correct the CompressFormat to JPG.

'contentValues.put(MediaStore.MediaColumns.DISPLAY_NAME, mCurrentImageFile.getName() + ".jpg")'

**Comment by polokoio456** [comment]
Because the DISPLAY_NAME and MIME_TYPE of ContentValue  are JPG format, I correct the CompressFormat to JPG.

**Comment by polokoio456** [comment]
Yeah, It's a good idea to add an overload, but I have no idea to implement it.

**Comment by Piasy** [comment]
Please check this commit: https://github.com/Piasy/BigImageViewer/commit/969f816b94cc36a98953bb90ed31e8b272d83474

**Pull request closed without merging**
