### PR TITLE
Fix BigImageView does not render in Android Studio layout editor

### PR DESCRIPTION
**Pull request by Blystad**
BigImageView would cause "Rendering Problems" in Android Studio
if one used the visual ("Design") editor.

### CODE REVIEW

**Comment by Blystad** [comment]
image

**Comment by Piasy** [comment]
Which version of Android studio do you use? I can't verify it.

**Comment by Blystad** [comment]
2.2.3

I've also confirmed it on 2.3.3, which is the latest version.

Just add

```
    <com.github.piasy.biv.view.BigImageView
        android:id="@+id/imgGalleryItem"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
```

to a layout (I'm using a RelativeLayout, but I don't think the type matters), click the "Design" tab, and it will fail.

**Comment by Piasy** [comment]
Ok, I think it's the problem of my support lib version or build tool version. If we set `mImageLoader = null` when `isInEditMode()`, would the preview work?

**Comment by Blystad** [comment]
Tested now, and, yes - it will work. If you prefer that route then I can update this PR with that change.

**Comment by Piasy** [comment]
Yes, please remove the dummy loader class

**Comment by Blystad** [comment]
Ok, see https://github.com/Piasy/BigImageViewer/pull/58

**Pull request closed without merging**
